name: Multiple-os-and-images

on: push

jobs:
    deploy-on-ubuntu:
        strategy:
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest , ubuntu-21.09]
            Images: [hello-world , alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run Images on ${{ matrix.os }}
              run: docker run ${{ matrix.Images }}
